'use client'

import { useEffect, useState } from 'react'

type Overview = { import: { status: string; rows: number; referential: string; created_at: string; duration: string }; quality: { code: string; severity: string; label: string; detail: string; count: number }[]; kpis: { label: string; value: string; trend: string; tone: string }[]; monthly: { month: string; value: number }[] }
const fallback: Overview = { import:{status:'success',rows:18420,referential:'ATIH MCO 2026',created_at:'2026-09-03T09:42:00Z',duration:'00:01:42'}, quality:[{code:'SCH-001',severity:'success',label:'Schéma reconnu',detail:'12 colonnes attendues, types conformes',count:0},{code:'DAT-014',severity:'warning',label:'Dates de sortie manquantes',detail:'Séjours sans date de sortie exploitable',count:24},{code:'DUP-003',severity:'error',label:'Doublons de séjours',detail:'Identifiants présents plusieurs fois',count:7}], kpis:[{label:'Séjours analysés',value:'18 420',trend:'+4,8 %',tone:'positive'},{label:'Durée moyenne',value:'4,6 j',trend:'−0,3 j',tone:'positive'},{label:'Taux de groupage',value:'97,2 %',trend:'+1,1 pt',tone:'positive'},{label:'Alertes ouvertes',value:'31',trend:'7 critiques',tone:'negative'}],monthly:[{month:'Avr',value:62},{month:'Mai',value:68},{month:'Juin',value:65},{month:'Juil',value:74},{month:'Août',value:78},{month:'Sept',value:86}] }

export default function Page() {
  const [data, setData] = useState<Overview>(fallback)
  const [active, setActive] = useState('Vue d’ensemble')
  const [demo, setDemo] = useState(true)
  useEffect(() => { fetch('/api/overview').then(r => r.ok ? r.json() : Promise.reject()).then(d => { setData(d); setDemo(false) }).catch(() => {}) }, [])
  const nav = ['Vue d’ensemble','Imports','Qualité des données','Datasets','Indicateurs','Traçabilité']
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">P</div><div><strong>PMSI Analytics</strong><span>Local-first DIM</span></div></div><div className="nav-label">ESPACE DE TRAVAIL</div><nav>{nav.map((item, i) => <button key={item} className={active===item?'nav-item active':'nav-item'} onClick={()=>setActive(item)}><span className="nav-icon">{['⌂','↥','✓','▤','◌','⌁'][i]}</span>{item}{item==='Qualité des données' && <b className="nav-count">31</b>}</button>)}</nav><div className="sidebar-bottom"><div className="privacy"><span className="dot"/>Données locales uniquement</div><button className="nav-item"><span className="nav-icon">⚙</span>Paramètres</button><div className="user"><div className="avatar">JD</div><div><strong>Jeanne Durand</strong><span>Médecin DIM</span></div><span className="more">•••</span></div></div></aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">MERCREDI 3 SEPTEMBRE 2026</p><h1>{active}</h1></div><div className="top-actions"><span className="local-status"><i/>Service local connecté</span><button className="icon-button" aria-label="Notifications">♧<b>3</b></button><button className="primary-button" onClick={()=>alert('Import local démarré')}>+ Nouvel import</button></div></header>
      <div className="content"><div className="notice"><div className="notice-icon">i</div><div><strong>Mode démonstration actif</strong><p>Les données affichées sont synthétiques. Importez un fichier PMSI pour commencer une analyse locale.</p></div><button onClick={()=>setDemo(false)}>Compris</button></div>
      <section className="section-heading"><div><h2>Vue d’ensemble</h2><p>Suivez la fraîcheur, la qualité et les principaux volumes de votre dernière base.</p></div><button className="outline-button">Dernier import <span>⌄</span></button></section>
      <div className="kpi-grid">{data.kpis.map(k=><article className="kpi" key={k.label}><div className="kpi-top"><span>{k.label}</span><span className="kpi-dots">•••</span></div><strong>{k.value}</strong><span className={k.tone==='negative'?'trend negative':'trend'}>{k.trend} <small>vs. période précédente</small></span></article>)}</div>
      <div className="grid-two"><section className="panel chart-panel"><div className="panel-header"><div><h3>Volume des séjours</h3><p>Évolution mensuelle · 6 derniers mois</p></div><span className="legend"><i/>Séjours</span></div><div className="chart"><div className="y-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="chart-area"><div className="grid-lines"/ ><svg viewBox="0 0 600 180" preserveAspectRatio="none" aria-label="Graphique du volume des séjours"><path d="M0 100 L120 85 L240 92 L360 62 L480 50 L600 20" fill="none" stroke="var(--primary)" strokeWidth="3"/><path d="M0 100 L120 85 L240 92 L360 62 L480 50 L600 20 V180 H0Z" fill="url(#fill)"/><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1d8b82" stopOpacity=".18"/><stop offset="1" stopColor="#1d8b82" stopOpacity="0"/></linearGradient></defs></svg><div className="x-axis">{data.monthly.map(m=><span key={m.month}>{m.month}</span>)}</div></div></div></section>
      <section className="panel import-panel"><div className="panel-header"><div><h3>Dernier import</h3><p>État du pipeline local</p></div><span className="status-pill success">Terminé</span></div><div className="import-file"><div className="file-icon">XLS</div><div><strong>pmsi_fixture_2026.csv</strong><span>Fixture synthétique · 18,4 k lignes</span></div><span className="check">✓</span></div><div className="import-rows"><div><span>Référentiel</span><strong>ATIH MCO 2026</strong></div><div><span>Durée</span><strong>{data.import.duration}</strong></div><div><span>Empreinte</span><strong className="mono">fixture-local…256</strong></div></div><button className="text-button">Voir le rapport d’import →</button></section></div>
      <section className="panel quality-panel"><div className="panel-header"><div><h3>Qualité des données</h3><p>Derniers contrôles exécutés sur <strong>sejours_normalises</strong></p></div><button className="outline-button small">Voir tous les contrôles</button></div><div className="quality-list">{data.quality.map(q=><div className="quality-row" key={q.code}><span className={'quality-status '+q.severity}>{q.severity==='success'?'✓':q.severity==='warning'?'!':'×'}</span><div><strong>{q.label}</strong><span>{q.detail}</span></div><span className={'severity '+q.severity}>{q.severity==='success'?'Conforme':q.severity==='warning'?'À surveiller':'Critique'}</span><span className="quality-count">{q.count || '—'}</span><span className="row-arrow">›</span></div>)}</div></section>
      <footer><span>Dernière synchronisation : il y a 2 min</span><span><i className="dot"/>Stockage local sécurisé · DuckDB + Parquet</span></footer>
      </div></main>
  </div>
}
